apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mlops-project
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: prabhav49/backend-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000