apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mlops-project   
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31562   
  type: NodePort        
